vim.keymap.set('n', '<leader>gp', '<CMD>Git push<CR>')
vim.keymap.set('n', '<leader>ga', '<CMD>Git add .<CR>')
vim.keymap.set('n', '<leader>gf', '<CMD>Git fetch origin<CR>')
vim.keymap.set('n', '<leader>gc', '<CMD>Telescope git_commits<CR>')
vim.keymap.set('n', '<leader>gC', '<CMD>Git commit<CR>')
vim.keymap.set('n', '<leader>gs', '<CMD>Telescope git_status<CR>')
vim.keymap.set('n', '<leader>gb', '<CMD>Telescope git_branches<CR>')
